# Generated by Django 5.0.1 on 2024-05-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_newslettersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
