# Generated by Django 5.0.1 on 2024-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_delete_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank='true', default='', max_length=254, null='true')),
            ],
        ),
    ]
