# Generated by Django 5.0.1 on 2024-05-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_newslettersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
